### ISSUE TITLE
Module #3: React Group Project (Kanban board set up)

### ISSUE THREAD

**Issue by karlavdelgadof** [Alzubair98/REACT-GROUP-PROJECT#29]
Hi there! :wave: 
![](https://media.giphy.com/media/BElb9DVpHezcZufOhl/giphy.gif)

Below you can find the link to our project :arrow_down: 
- [Our board](https://github.com/Alzubair98/REACT-GROUP-PROJECT/projects/1) :bookmark_tabs: 

#### Our Team :technologist: :muscle: 
- @karlavdelgadof :bust_in_silhouette: 
- @Alzubair98 :bust_in_silhouette:

**Comment by mugishasam123** [comment]
Hi team 👋 , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![alt](https://c.tenor.com/CLBmh64a3woAAAAC/so-close-dismay.gif)

## Highlights
- Descriptive issue title 👍 
- Descriptive summary 🚀 


## Required Changes ♻️

- [ ] Please make sure to remove your issues from the done section to the todo section as you will be starting this project soon,so it will be a good idea because it will help you keep track of your project progress.

ToDO:
![image](https://user-images.githubusercontent.com/90524466/185991218-e872f68c-c746-41f4-8560-5161398030e4.png)

Done:
![image](https://user-images.githubusercontent.com/90524466/185991304-227f2d28-9d4b-4abf-be81-325179ecf683.png)

- [ ] Kindly remove the cards for team member 3 as you will be progressing as a team of two, so it will be a good idea to not confuse yourselves by removing cards of third team member.you got this 👍 

_Check the comments under the review._

## Optional suggestions
-  N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by karlavdelgadof** [comment]
@mugishasam123 My apologies, the link was wrong, could you check again :pray: ?

**Comment by aimemalaika** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
